# networks:
#   server_network:
#     name: server_network
#     external: true

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    user: 1000:1000
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.11
        ipv6_address: 2001:db8:1::11
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql
    environment:
      TZ: ${TZ}
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_USER: ${POSTGRES_SU_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_SU_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SU_DATABASE_NAME}
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          pg_isready -U ${POSTGRES_SU_USERNAME}
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    shm_size: 128mb

  caddy:
    image: caddy:2
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.2
        ipv6_address: 2001:db8:1::2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CADDY_CONFIG_PATH}:/config
      - ${CADDY_DATA_PATH}:/data
    environment:
      - TZ=${TZ}
