name: media

services:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.101
        ipv6_address: 2001:db8:1::101
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ../data/qbit/:/config
      - /Volumes/etmnt/downloads:/media/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.rule=Host(`qbit.lan`)"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.104
        ipv6_address: 2001:db8:1::104
    volumes:
      - ../data/sonarr:/config
      - /Volumes/etmnt/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.lan`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.105
        ipv6_address: 2001:db8:1::105
    volumes:
      - ../data/radarr:/config
      - /Volumes/etmnt/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.lan`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.106
        ipv6_address: 2001:db8:1::106
    ports:
      # Ports for discovery
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - ../data/jellyfin:/config
      - /Volumes/etmnt/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=jellyfin.lan #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.lan`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      server_network:
        ipv4_address: 172.18.0.100
        ipv6_address: 2001:db8:1::100
    volumes:
      - ./homepage/:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.lan`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  server_network:
    name: server_network
    external: true
