name: scraper

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn # or wireguard
      - OPENVPN_USER=9y3jcA1ZKRKz1mDFSf2WRMpr
      - OPENVPN_PASSWORD=pT7NxdRGywAJXBqWc21d2qno
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HTTPPROXY=on
    ports:
      - 9696:9696/tcp
      - 8888:8888/tcp

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: service:vpn
    volumes:
      - ../data/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.lan`)"
  #     - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"


  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   user: "1000:1000"
  #   restart: unless-stopped
  #   networks:
  #     server_network:
  #       ipv4_address: 172.18.0.102
  #       ipv6_address: 2001:db8:1::102
  #   ports:
  #     - "8191:8191"
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #     - LOG_HTML=${LOG_HTML:-false}
  #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  #     - TZ=${TZ}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.lan`)"
  #     - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"

  # prowlarr:
  #   image: lscr.io/linuxserver/prowlarr:latest
  #   container_name: prowlarr
  #   restart: unless-stopped
  #   networks:
  #     server_network:
  #       ipv4_address: 172.18.0.103
  #       ipv6_address: 2001:db8:1::103
  #   ports:
  #     - 9696:9696
  #   volumes:
  #     - ../data/prowlarr:/config
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.lan`)"
  #     - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
