services:
  # Beszel
  # Ports: 8090
  beszel:
    user: 1000:1000
    image: henrygd/beszel:0.18
    container_name: beszel
    hostname: beszel
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.1.3
        ipv6_address: 2001:db8:1::103
    ports:
      - 8090:8090
    volumes:
      - ${LCL_BESZEL_DATA}:/beszel_data
      - ${LCL_BESZEL_SOCKET}:/beszel_socket
    environment:
      TZ: ${TZ}
    healthcheck:
      test: [ "CMD", "/beszel", "health", "--url", "http://beszel:8090" ]
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.225274.xyz`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.http.routers.beszel.tls.certresolver=letsencrypt"
