services:

  # Runs on port 8088
  qbit:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbit
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.2.1
        ipv6_address: 2001:db8:1::201
    ports:
      - "8088:8088"
      # Discovery ports
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ${LCL_QBIT_CONFIG}:/config
      - ${LCL_QBIT_DOWNLOADS}:/media/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.14
    container_name: sonarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.2.11
        ipv6_address: 2001:db8:1::211
    ports:
      - "8989:8989"
    volumes:
      - ${LCL_SONARR_CONFIG}:/config
      - ${EXT_MEDIA_DATA}:/media
      - ${LCL_QBIT_DOWNLOADS}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  radarr:
    image: lscr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.2.12
        ipv6_address: 2001:db8:1::212
    ports:
      - "7878:7878"
    volumes:
      - ${LCL_RADARR_CONFIG}:/config
      - ${EXT_MEDIA_DATA}:/media
      - ${LCL_QBIT_DOWNLOADS}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.2.20
        ipv6_address: 2001:db8:1::220
    ports:
      - "8096:8096"
    volumes:
      - ${LCL_JELLYFIN_CONFIG}:/config
      - ${EXT_MEDIA_DATA}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
