name: server

networks:
  server_network:
    name: server_network
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        - subnet: 2001:db8:1::/64

include:
  - docker-compose-utilities.yml
  - docker-compose-monitor.yml
  - docker-compose-media.yml
