name: server

networks:
  server_network:
    name: server_network
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        - subnet: 2001:db8:1::/64

services:

  # Reverse Proxy - Traefik
  traefik:
    image: traefik:v3.4
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.1.2
        ipv6_address: 2001:db8:1::102
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/dynamic.yml:/config/dynamic.yml:ro
      - ./config/traefik/htpasswd:/config/htpasswd:ro
      - traefik-letsencrypt:/letsencrypt
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}

volumes:
  traefik-letsencrypt:
    name: traefik-letsencrypt

include:
  - docker-compose-utilities.yml
  # - docker-compose-monitor.yml
  # - docker-compose-media.yml
