services:

  qbit:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbit
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.101
        ipv6_address: 2001:db8:1::101
    ports:
      - "8088:8088"
      # Discovery ports
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ${QBIT_CFG_PATH}:/config
      - ${QBIT_DOWNLOADS_PATH}:/media/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881

  # Runs on port 8191
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.25
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.102
        ipv6_address: 2001:db8:1::102
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}

  # Runs on port 9696
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.37.0
    container_name: prowlarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.103
        ipv6_address: 2001:db8:1::103
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CFG_PATH}:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.14
    container_name: sonarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.111
        ipv6_address: 2001:db8:1::111
    ports:
      - "8989:8989"
    volumes:
      - ${SONARR_CFG_PATH}:/config
      - ${USER_MEDIA_PATH}:/media
      - ${QBIT_DOWNLOADS_PATH}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  radarr:
    image: lscr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.112
        ipv6_address: 2001:db8:1::112
    ports:
      - "7878:7878"
    volumes:
      - ${RADARR_CFG_PATH}:/config
      - ${USER_MEDIA_PATH}:/media
      - ${QBIT_DOWNLOADS_PATH}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    restart: unless-stopped
    networks:
      server_network:
        ipv4_address: 172.18.0.120
        ipv6_address: 2001:db8:1::120
    ports:
      - "8096:8096"
    volumes:
      - ${JELLYFIN_CFG_PATH}:/config
      - ${USER_MEDIA_PATH}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
