entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: server_network
  file:
    filename: /config/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: akashgurava@outlook.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: INFO
accessLog: {}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/origin-cert.pem
        keyFile: /certs/origin-key.pem

api:
  dashboard: true
  insecure: false
