global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'blocky'
    static_configs:
    - targets: ['192.168.1.2:4000']

  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['192.168.1.2:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['172.18.0.8:8080']

  # - job_name: 'traefik'
  #   static_configs:
  #     - targets: ['192.168.1.2:8080']

  # - job_name: 'glances_exporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['172.18.0.12:9091']
