upstreams:
  init:
    strategy: fast
  groups:
    default:
      - 9.9.9.9
      - 1.1.1.1
  strategy: strict
  timeout: 2s

bootstrapDns:
  - upstream: https://9.9.9.9/dns-query

blocking:
  denylists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
  clientGroupsBlock:
    default:
      - ads
      - special

customDNS:
  mapping:
    blocky.lan: 192.168.1.2
    traefik.lan: 192.168.1.2
    pgweb.lan: 192.168.1.2
    node-exporter.lan: 192.168.1.2
    cadvisor.lan: 192.168.1.2
    prometheus.lan: 192.168.1.2
    grafana.lan: 192.168.1.2
    glances.lan: 192.168.1.2
    qbit.lan: 192.168.1.2
    flaresolverr.lan: 192.168.1.2
    prowlarr.lan: 192.168.1.2
    sonarr.lan: 192.168.1.2
    radarr.lan: 192.168.1.2
    jellyfin.lan: 192.168.1.2
    homepage.lan: 192.168.1.2

clientLookup:
  upstream: 192.168.1.1
  clients:
    server:
      - 172.18.0.1
      - 192.168.1.2
    macair:
      - 192.168.1.3
    macpro:
      - 192.168.1.4
    S23 Ultra:
      - 192.168.1.5
    Wipro PC Station:
      - 192.168.1.200
    # Docker Services
    traefik:
      - 172.18.0.2
    postgres:
      - 172.18.0.11
    prometheus:
      - 172.18.0.12
    redis:
      - 172.18.0.13

caching:
  minTime: 0s
  maxTime: 0s
  maxItemsCount: 0
  cacheTimeNegative: -1

log:
  level: info
  format: text
  timestamp: true
  privacy: false

queryLog:
  type: postgresql
  target: postgres://blocky_admin:UAzjPRB2*XYg&s@192.168.1.2:5432/blocky
  logRetentionDays: 30

prometheus:
  enable: true
  path: /metrics

ports:
  dns: 53
  http: 4000
