entryPoints:
  web:
    address: :80
    http2:
      maxConcurrentStreams: 250

accesslog:
  format: json

log:
  level: INFO
  format: json

api:
  insecure: true
  dashboard: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

ping: {}

providers:
  docker:
    defaultRule: Host(`{{ .Name }}.lan`)
    exposedByDefault: false
